services:
  web-event-finder-db:
    image: postgres:17
    container_name: web-event-finder-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - web-event-finder-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  web-event-finder-db:
